@url = https://ddjejmwwrb.execute-api.ap-south-1.amazonaws.com/prod/
@token = eyJraWQiOiJHcVhwZHI4ckQxQUNabGg0MjhvY21XQzVWNnBBS2JJR1owUWRmXC9vNjB5Yz0iLCJhbGciOiJSUzI1NiJ9.eyJvcmlnaW5fanRpIjoiNGU1MGM4MjktMzk5OS00YzY5LWJjMzUtYjNmZjIxNThjZDNhIiwic3ViIjoiOTEwMzZkZmEtMzAxMS03MGU2LTI2MTItODQwYjQ0NzljZWRlIiwiYXVkIjoiMmpva2hyMzhzNDRoY2NsNXI5c21jMDVudSIsImV2ZW50X2lkIjoiMDI2MmMzNzctMjdjZS00ODE0LWJjYWYtZjAyYWYxZTdhMjJkIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2ODc5NDAwMTcsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5hcC1zb3V0aC0xLmFtYXpvbmF3cy5jb21cL2FwLXNvdXRoLTFfRzlLZ3ZmQ29IIiwiY29nbml0bzp1c2VybmFtZSI6InJpY2t5IiwiZXhwIjoxNjg3OTQzNjE3LCJpYXQiOjE2ODc5NDAwMTcsImp0aSI6IjQzN2RhNDFjLTg2OWItNDUxMy04MGI3LWUyMmFhOWI0NDI1MCJ9.sBOnWET_fXMfLRx0MI6v9O7j3Rj0z8Gr7voc9nJfERaU3BN0iTPSzis7WGWlS9YYng3KPn6LvR7zKBhmNgAwqMLaof2svNAru__sL0ItBW_B5pVtQhQHc7-EVnKX-em1id-coCARqvDgaDZ4liT1VAXO8aNDQXaDUje79AmKLrjBr3puhJot-M-bMZhgbGtav0ybDIpX_k4HbZQfwVNSNJg2mYklnHYQIJSqTb85G9mXCTMZt9HnF3fMnd25CQxHUKqrCqyQ2E8Iu853JhCgApSi8qi-IdEqAIy8ro_AuoWr_NC-UQyYGsCdTAQe03lweGdBkHu8Sgzqk_K2sJtcmA

GET {{url}}/get-items
###

GET {{url}}/get-user
Authorization: {{token}}
###